name: Cross account ecr image

on:
  workflow_call:
    inputs:
      ecr-registry:
        required: true
        type: string
      ecr-repo-name:
        required: true
        type: string
      aws-region:
        required: true
        type: string
        default: ap-southeast-1
      role-to-assume:
        required: true
        type: string
      role-session-name:
        required: true
        type: string
      role-duration-seconds:
        required: true
        type: number
        default: 1200
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  cross-account-ecr-image:
    name: cross-account-ecr-image
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws-region }}
          role-to-assume: ${{ inputs.role-to-assume }}
          role-session-name: ${{ inputs.role-session-name }}
          role-duration-seconds: ${{ inputs.role-duration-seconds }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        id: login-ecr

      - name: Set image
        run: |
          echo "FROM_IMAGE=${{ inputs.ecr-registry }}/${{ inputs.ecr-repo-name }}:${{ github.ref_name }}" >> $GITHUB_ENV
          echo "TO_IMAGE=${{ steps.login-ecr.outputs.registry }}/${{ inputs.ecr-repo-name }}:${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Pull image from another account
        run: |
          docker pull $FROM_IMAGE

      - name: Tag
        run: |
          docker tag $FROM_IMAGE $TO_IMAGE

      - name: push image to ECR
        run: |
          docker push $TO_IMAGE
