name: Cross account ecr image

on:
  workflow_call:
    inputs:
      ecr-registry:
        required: true
        type: string
      ecr-repo-name:
        required: true
        type: string
      pull-platforms: 
        type: string
        default: linux/arm64
      aws-region:
        required: true
        type: string
        default: ap-southeast-1
      role-to-assume:
        required: true
        type: string
      role-session-name:
        required: true
        type: string
      role-duration-seconds:
        required: true
        type: number
        default: 1200

jobs:
  cross-account-ecr-image:
    name: cross-account-ecr-image
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ inputs.aws-region }}
          role-to-assume: ${{ inputs.role-to-assume }}
          role-session-name: ${{ inputs.role-session-name }}
          role-duration-seconds: ${{ inputs.role-duration-seconds }}

      - name: Set source image
        run: |
          echo "SOURCE_IMAGE=${{ inputs.ecr-registry }}/${{ inputs.ecr-repo-name }}:${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Login to source ECR
        run: |
          aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin ${{ inputs.ecr-registry }}

      - name: Pull image from another account
        run: |
          docker pull --platform ${{ inputs.pull-platforms }} $SOURCE_IMAGE 

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr

      - name: Set destination image
        run: |
          echo "DESTINATION_IMAGE=${{ steps.login-ecr.outputs.registry }}/${{ inputs.ecr-repo-name }}:${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Tag
        run: |
          docker tag $SOURCE_IMAGE $DESTINATION_IMAGE

      - name: push image to ECR
        run: |
          docker push $DESTINATION_IMAGE
