name: Deploy to K8s

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      docker-image:
        required: true
        type: string
      docker-tag:
        required: true
        type: string
      matrix-path:
        required: true
        type: string
      tf-version:
        required: false
        type: string
        default: '1.4.6'
      tg-version:
        required: false
        type: string
        default: '0.50.8'
      aws-region:
        required: true
        type: string
        default: ap-southeast-1
      role-to-assume:
        required: true
        type: string
      role-session-name:
        required: true
        type: string
      role-duration-seconds:
        required: true
        type: number
        default: 1200
    secrets:
      GH_ACTIONS_PRIVATE_KEY:
        required: true
      GH_PAT:
        required: true

jobs:
  terragrunt-apply:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        path: ${{ fromJson(inputs.matrix-path) }}
    env:
      WORKING_DIR: ${{ github.workspace }}/terragrunt/${{ inputs.environment }}/${{ matrix.path }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.GH_PAT }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ inputs.aws-region }}
          role-to-assume: ${{ inputs.role-to-assume }}
          role-session-name: ${{ inputs.role-session-name }}
          role-duration-seconds: ${{ inputs.role-duration-seconds }}

      - name: Terragrunt Init
        uses: gruntwork-io/terragrunt-action@v2.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          INPUT_PRE_EXEC_1: |
            git config --global url."https://github-machine-token:${{secrets.GH_PAT}}@github.com".insteadOf "https://github.com"
          INPUT_PRE_EXEC_2: |
            git config --global url."https://github-machine-token:${{secrets.GH_PAT}}@github.com".insteadOf "ssh://git@github.com"
        with:
          tf_version: ${{ inputs.tf-version }}
          tg_version: ${{ inputs.tg-version }}
          tg_dir: ${{ env.WORKING_DIR }}
          tg_command: init -upgrade

      - name: Enable GitHub Debug Mode
        run: |
          echo "Enabling debug mode"
        if: ${{ always() }}

      - name: Terraform Apply
        uses: gruntwork-io/terragrunt-action@v2.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          DOCKER_IMAGE: ${{ inputs.docker-image }}
          DOCKER_TAG: ${{ inputs.docker-tag }}
        with:
          tf_version: ${{ inputs.tf-version }}
          tg_version: ${{ inputs.tg-version }}
          tg_dir: ${{ env.WORKING_DIR }}
          tg_command: apply -auto-approve --terragrunt-debug
