name: Deploy Firebase Functions

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      workload_identity_provider:
        required: true
        type: string
      service_account:
        required: true
        type: string
      function_name:
        required: true
        type: string
      aws-region:
        required: true
        type: string
        default: ap-southeast-1
      role-to-assume:
        required: true
        type: string
      role-session-name:
        required: true
        type: string
      role-duration-seconds:
        type: number
        default: 1200
    secrets:
      GH_PAT:

jobs:
  deploy:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.GH_PAT || github.token }}

      - uses: pnpm/action-setup@v4
        name: prepare pnpm
        id: prepare-install
        with:
          version: 9
          run_install: false

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install pnpm
        run: cd ./functions && pnpm install

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Firebase CLI
        run: pnpm install -g firebase-tools is-ci

      - id: authen-gcp
        name: GCP Authentication
        uses: google-github-actions/auth@v2
        with:
          service_account: ${{ inputs.service_account }}
          workload_identity_provider: ${{ inputs.workload_identity_provider }}
          create_credentials_file: true
          export_environment_variables: true

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ inputs.aws-region }}
          role-to-assume: ${{ inputs.role-to-assume }}
          role-session-name: ${{ inputs.role-session-name }}
          role-duration-seconds: ${{ inputs.role-duration-seconds }}

      - name: Install SOPS
        run: |
          curl -LO https://github.com/getsops/sops/releases/download/v3.9.2/sops-v3.9.2.linux.amd64
          mv sops-v3.9.2.linux.amd64 /usr/local/bin/sops
          chmod +x /usr/local/bin/sops

      - name: Sops Decrypt
        run: sops -d functions/secrets/${{ inputs.env }}.secrets.enc > functions/.env

      - name: use Project
        run: firebase use ${{ inputs.env }}

      - id: Deploy
        run: firebase deploy --only functions -P ${{ inputs.env }}
