name: Deploy Firebase Functions

on:
  workflow_call:
    inputs:
      workload_identity_provider:
        required: true
        type: string
      service_account:
        required: true
        type: string
      function_name:
        required: true
        type: string
    secrets:
      GH_PAT:
        required: true

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.GH_PAT || github.token }}

      - name: Auth GCP 
        id: auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ inputs.workload_identity_provider }}
          service_account: ${{ inputs.service_account }}

    #   - name: 'Deploy functions'
    #     id: 'deploy'
    #     uses: 'google-github-actions/deploy-cloud-functions@v2'
    #     with:
    #       name: ${{ inputs.function_name }}
    #       runtime: 'nodejs20'
    #       region: 'asia-southeast1'
