name: Deploy Firebase Functions

on:
  workflow_call:
    inputs:
      workload_identity_provider:
        required: true
        type: string
      service_account:
        required: true
        type: string
      function_name:
        required: true
        type: string
    secrets:
      GH_PAT:
        required: true

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.GH_PAT || github.token }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        id: pnpm-install
        with:
          version: 9
          run_install: |
            - recursive: true

      - name: Install Firebase CLI
        run: pnpm install -g firebase-tools

      - id: auth
        name: GCP Authentication
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ inputs.workload_identity_provider }}
          service_account: ${{ inputs.service_account }}
          create_credentials_file: true
          export_environment_variables: true
          access_token_lifetime: 60s

      - name: echo $GOOGLE_APPLICATION_CREDENTIALS
        run: echo $GOOGLE_APPLICATION_CREDENTIALS

      - name: cat $GOOGLE_APPLICATION_CREDENTIALS
        run: cat $GOOGLE_APPLICATION_CREDENTIALS

      # - name: Login to Firebase
      #   run: firebase login:ci

      # - name: Verify Firebase Auth
      #   run: firebase projects:list

      - id: deploy
        run: firebase deploy --only functions
