name: Deploy Firebase Functions

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      workload-identity-provider:
        required: true
        type: string
      service-account:
        required: true
        type: string
      aws-region:
        required: true
        type: string
        default: ap-southeast-1
      role-to-assume:
        required: true
        type: string
      role-session-name:
        required: true
        type: string
      role-duration-seconds:
        type: number
        default: 1200
      gcp-project:
        required: true
        type: string
      gcp-region:
        required: true
        type: string
    secrets:
      GH_PAT:

jobs:
  deploy:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.GH_PAT || github.token }}

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        id: setup-pnpm
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
          cache-dependency-path: functions/pnpm-lock.yaml

      - name: Install firebase-tools is-ci
        run: pnpm install -g firebase-tools is-ci

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: ./functions

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - id: auth-gcp
        name: GCP Authentication
        uses: google-github-actions/auth@v2
        with:
          service_account: ${{ inputs.service-account }}
          workload_identity_provider: ${{ inputs.workload-identity-provider }}
          create_credentials_file: true
          export_environment_variables: true

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"
        with:
          version: ">= 363.0.0"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ inputs.aws-region }}
          role-to-assume: ${{ inputs.role-to-assume }}
          role-session-name: ${{ inputs.role-session-name }}
          role-duration-seconds: ${{ inputs.role-duration-seconds }}

      - name: Install SOPS
        run: |
          curl -LO https://github.com/getsops/sops/releases/download/v3.9.2/sops-v3.9.2.linux.amd64
          mv sops-v3.9.2.linux.amd64 /usr/local/bin/sops
          chmod +x /usr/local/bin/sops

      - name: Sops Decrypt
        run: sops -d ./secrets/${{ inputs.env }}.secrets.enc > .env
        working-directory: ./functions

      - name: use Project
        run: firebase use ${{ inputs.env }}

      - id: Deploy
        run: firebase deploy --only functions -P ${{ inputs.env }}

      - name: Verify Cloud Functions
        run: |
          # Wait for a short period to allow for service propagation
          sleep 30

          # List all Firebase Functions and check their status
          FUNCTIONS=$(gcloud functions list --project ${{ inputs.gcp-project }} --regions ${{ inputs.gcp-region }} --format "value(name)")

          for FUNCTION in $FUNCTIONS; do
            echo "Checking function: $FUNCTION"
            
            # Get function status using Firebase CLI
            STATE=$(gcloud functions describe $FUNCTION --region ${{ inputs.gcp-region }} --format "value(state)")

            if [ "$STATE" = "ACTIVE" ]; then
              echo "✅ Function $FUNCTION is running successfully"
            else
              echo "❌ Function $FUNCTION failed to start properly"
              echo "State: $STATUS"
              exit 1
            fi
          done

          echo "All Firebase Functions verified successfully!"
