name: Test

on:
  workflow_call:
    inputs:
      directory-path:
        required: false
        type: string

jobs:
  test:
    runs-on: 4-core-arm64-GitHub-hosted-runners
    defaults:
      run:
        working-directory: ${{ inputs.directory-path || './' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        id: pnpm-install
        with:
          version: 9
          run_install: false

      - uses: actions/setup-node@v4
        name: Install Node.js
        with:
          node-version: 22
          cache: "pnpm"
          cache-dependency-path: ${{ inputs.directory-path && format('{0}/pnpm-lock.yaml', inputs.directory-path) || '' }}

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - run: pnpm lint
      - run: pnpm test:cov

      - name: Upload test coverage artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-coverage
          path: coverage
